---
# MySQL 通用角色元数据
galaxy_info:
  author: "Ansible Automation"
  description: "MySQL/MariaDB 通用安装和配置角色"
  company: ""
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - database
    - mysql
    - mariadb
dependencies: []
