---
galaxy_info:
  role_name: nginx_proxy
  author: DevOps Team
  description: Nginx 反向代理与负载均衡管理角色
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions: ['7', '8', '9']
    - name: Debian
      versions: ['buster', 'bullseye']
    - name: Ubuntu
      versions: ['focal', 'jammy']
  galaxy_tags:
    - nginx
    - proxy
    - loadbalancer

dependencies: []
